# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    
      - name: Git Checkout
        uses: actions/checkout@v3
    
      - name: Building Python Environment
        run: |
          chmod 700 ./ci/env_setup.sh
          ./ci/env_setup.sh
          
      - name: Seeing output folders
        run: |
          pwd
          ls -l
          echo "seeing into ci"
          ls -l ci
          
      - name: Seeing hostname
        run: hostname -I
          
      
      - name: Running Docker Compose Orion-v2
        run: |
          cd ./ci/orion/
          docker compose up -d
          cd /home/runner/work/fiware-orion-pyspark-connector/fiware-orion-pyspark-connector
          sleep 30
          hostname=$(hostname -I | tr ' ' '\n' | grep 10)
          sed -i "s/0.0.0.0/$hostname/g" ./ci/subscription.json
          curl -X POST http://localhost:1026/v2/entities/ -d @./ci/new_entity.json --header "Content-Type: application/json"
          curl -X POST http://localhost:1026/v2/subscriptions/ -d @./ci/subscription.json --header "Content-Type: application/json" 
          
          

#      - name: Raw Test
#        run: |
#          sleep 10
 #         chmod 700 ./ci/raw_test/raw_test.sh
  #        ./ci/raw_test/raw_test.sh
          
          
      - name: V2 Tests
        run: |
          sleep 10
          chmod 700 ./ci/v2_test/v2_test.sh
          ./ci/v2_test/v2_test.sh




# Runs a set of commands using the runners shell
#- name: Run a multi-line script
#  run: |
#    echo Add other actions to build,
#    echo test, and deploy your project.
